config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'pages#home'
    # this is the final and good code
    # resources :collections do
    #   resources :tags
    # end
    resources :collections do
      resources :reviews
      resources :tag_collections, only: [:destroy]
    end

    resources :tag_collections, only: [:create, :destroy]
    resources :tags
    resources :users
    resources :movies, only: [:show]
    resources :tag_collections, only: [:create]
    resources :friendships
    #post "search", to: "pages#search"
    # get "friends", to: "pages#friends"
    get "about", to: "pages#about"
    get "results", to: "pages#results"
    get "search", to: "pages#search"
    get "pending", to: "friendships#pending"
    get "sent", to: "friendships#sent"
    get "profile", to: "pages#profile"

     # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq' # warning everyone has access to this.. please consult the lecture notes ..lambda { |u| u.admin }
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :user

  has_many :reviews, dependent: :destroy
  has_many :tags, through: :tag_collections
  has_many :tag_collections, dependent: :destroy

  validates :movie_id, :user_id, presence: true
  validates :movie_id, uniqueness: {scope: :user_id}
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
    before_action :set_collection, only: [:show,:mycollection]
  def index
    if params[:tag_id]
      @collections = Tag.find(params[:tag_id]).collections
    else
      @collections = current_user.collections
    end
  end

  def show
    @review = Review.new
    @movie = @collection.movie
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    @collection.save
    redirect_to collections_path(@collection)
  end


  # def edit
  #   @collection = Collection.find(params[:id])
  # end

  # def update
  #   @collection = Collection.find(params[:id])
  #   @collection.update(collection_params)
  # #   redirect_to collections_path(@collection)
  # end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to collections_path
  end

  private
  def set_collection
    @collection = Collection.find(params[:id])
  end
  def collection_params
    params.require(:collection).permit(:movie_id, :media)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper

  # def add_movie_details
    # render 'pages/results_movie_content' if current_user.collection?
  # end

   # def add_review_form
    # render 'collections/review_form' if current_user.collection?
  # end
end

app/views/collections/_add_tag_collection.html.erb
<div class="row">
  <div class="container">
    <div class="col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3  ">
      <h5>My movies</h5>
      <div class="movie-list-card">
        <% @collections.each do |collection| %>
          <%= cl_image_tag collection.movie.photo_url, height: 100, crop: :fill %>
          <%= label_tag collection.id do %>
            <%= check_box_tag collection.id%>
           <%= collection.movie %>
          <%end%>
        <%end%>
      </div>

    </div>
  </div>

</div>

app/views/collections/_collection_menus.html.erb
<div class="collection-menu">
  <%= link_to 'View', collections_path%></br>
  <%= link_to 'Create', new_tag_path%></br>
  <a>Review</a></br>
  <a>Share</a>
</div>
<div class="list-menu">
  <a>All</a></br>
  <a>#list1</a></br>
  <a>#list2</a></br>
  <a>#list3</a>
</div>

app/views/collections/_review_form.html.erb
    <div class="col-xs-12 col-sm-8 results-content-bg">
      <div class="row">
        <div class="col-sm-3 col-xs-12 center">
         <strong>Plot:</strong>
       </div>
       <div class="col-sm-9 col-xs-12">
        <%= @movie.synopsis %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3 col-xs-12 center">
       <strong>Directors:</strong>
     </div>
     <div class="col-sm-9 col-xs-12">
       <%= @movie.director%>
     </div>
   </div>


   <div class="row">
    <div class="col-sm-3 col-xs-12 center">
     <strong>Actors:</strong>
   </div>
   <div class="col-sm-9 col-xs-12">
    <%= @movie.actor %>
  </div>
</div>

<div class="row">
  <div class="col-sm-3 col-xs-12 center">
   <strong>Genre: </strong>
 </div>
 <div class="col-sm-9 col-xs-12">
  <%= @movie.genre %>
</div>
</div>

<div class="row">
  <div class="col-sm-3 col-xs-12 center">
   <strong>Rated: </strong>
 </div>
 <div class="col-sm-9 col-xs-12">
  <%= @movie.rated %>
</div>
<div class="col-sm-9 col-xs-12">
  <%= simple_form_for [@collection, @review], html: { class: "review-form"} do |f| %>
  <%= f.input_field :my_rating, as: :integer, class: "form-control", placeholder: '1-5', label: false, class: 'review-tiny' %>
  <%= f.input_field :phrase, as: :string, class: "form-control", placeholder: 'type your review', label: false, class: 'review'%>
  </div>
  <div class="col-sm-9 col-xs-12 text-center">
  <%= f.submit "Publish review", class: "btn add-to-col", path: collections_path%>
  <% end %>
</div>
</div>

app/views/collections/index.html.erb
<% content_for :meta_title , "This is my collection on Mustachio" %>
<% content_for :meta_description, "Go check it out and build yours!" %>
<% content_for :meta_image , "logo-meta.png" %>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=774775452673834";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="search-section text-center" style='padding-top:80px;'>
  <!-- search -->
  <h2>Add a movie</h2>
  <%= simple_form_for :movie, method: :get, url: search_path do |f|%>
  <%= f.input :title, input_html: {class: 'chosen-select form-control'}, prompt: 'which title?', placeholder: 'which title?',label: false  %>
  <%= f.input :year, input_html: {class: 'chosen-select form-control'}, prompt: '(which year?)', placeholder: 'which year(optional)?',label: false  %>
  <% image_submit_tag("logo-white.png", class: 'image-responsive search-logo') %>
  <%= f.submit "Search", class: "btn" %>
  <% end %>
</div>


<div class="container movies-container">

  <div class="list-navs">
    <%= link_to collections_path, class: "list-nav #{params[:tag_id] ? '' : 'active'}" do %>
    All <span class="movie-counter"><%= current_user.collections.count %></span>
      <div class="fb-share-button"
      data-href="http://www.muustachio.com/users/<%= current_user.id %>"
      data-layout="button">
  </div>
    <% end %>
    <!-- tag list navbar -->
    <% current_user.tags.distinct.take(3).each do |tag| %>
    <%= link_to collections_path(tag_id: tag.id), class: "list-nav #{(params[:tag_id].to_i == tag.id )  ? 'active' : ''  }" do %>
    <%= tag.name  %> <span class="movie-counter"><%=  tag.collections.count %></span>
    <% end %>
    <% end %>
    <%= link_to new_tag_path, class: "list-nav list-btn" do %>
    Add movie list <i class="fa fa-plus"></i>
    <% end %>
  </div>
<!-- start of collections-->
  <div class="movies">
    <% if @collections.size == 0 %>
    <p class="no-movie">No movies yet in your collection!</p>
    <% else %>
    <% @collections.reverse.each do |collection| %>

    <div class="movie-item">
      <div class="movie-picture" style="background-image: url('<%= collection.movie.photo_url %>')"></div>
      <div class="movie-body">
        <h3><%= collection.movie.title + ' (' + collection.movie.year.to_s + ")" %></h3>

        <p>
          <% unless collection.reviews.empty? %>
          <% collection.reviews.first.my_rating.to_i.times do %>
          <i class="fa fa-star yellow"></i>
          <% end %>
          <% (5 - collection.reviews.first.my_rating.to_i).times do %>
          <i class="fa fa-star grey"></i>
          <% end %>
          <span>(<%= collection.reviews.empty? ? '' : collection.reviews.first.phrase %>)</span>
          <% end %>
        </p>
        <p><%= collection.movie.synopsis %></p>
        <% unless current_user.tags.empty? %>
        <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#collection-<%= collection.id %>">
          Add to list <i class="fa fa-plus"></i>
        </button>
        <% end %>

      </div>
      <div class="movie-actions">
        <%= link_to collection_path(collection) do %>
        <i class="fa fa-eye"></i>
        <% end %>

        <!-- this is where the tag_collection needs to be deleted -->

        <%= link_to collection_path(collection), method: :delete do %>
        <i class="fa fa-trash"></i>
        <% end %>
      </div>
    </div>

    <%end%>

    <% end %>
    <!-- end of collections, this should be exported as a partial-->
  </div>
<!-- end of movies div-->
</div>



<% @collections.each do |collection| %>
<!-- Add to list Modal -->
<div class="modal fade modal-movie" id="collection-<%= collection.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Add to a list</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for TagCollection.new do |f| %>
        <%= f.input :tag_id, collection: current_user.tags.distinct.reject {|t| collection.tags.include? t }, prompt: "Choose a list", label: false    %>
        <%= f.input :collection_id, as: :hidden, input_html: { value: collection.id }  %>
        <%= f.submit "Add to list", class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>



<!-- <div class="movie-list-card">

</div> -->

app/views/collections/mycollection.html.erb
<%= render 'pages/results_form', review: "collections/review_form" %>

app/views/collections/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <p><%= @collection.movie.title %></p>
      <p><%= @collection.movie.year %></p>

      <p><% @collection.tags.each do |tag|%></p>
      <p><%= tag.name%></p>
      <%end%>
      <%= render 'review_form' %>
    </div>
  </div>
</div>