config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'pages#home'
    # this is the final and good code
    # resources :collections do
    #   resources :tags
    # end
    resources :collections do
      resources :reviews
      resources :tag_collections, only: [:destroy]
    end

    resources :tag_collections, only: [:create, :destroy]
    resources :tags
    resources :users
    resources :movies, only: [:show]
    resources :tag_collections, only: [:create]
    resources :friendships
    #post "search", to: "pages#search"
    # get "friends", to: "pages#friends"
    get "about", to: "pages#about"
    get "results", to: "pages#results"
    get "search", to: "pages#search"
    get "pending", to: "friendships#pending"
    get "sent", to: "friendships#sent"
    get "profile", to: "pages#profile"

     # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq' # warning everyone has access to this.. please consult the lecture notes ..lambda { |u| u.admin }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, UserPhotoUploader

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]

  has_many :tags, through: :collections, dependent: :destroy
  has_many :tag_collections, through: :collections
  has_many :collections, dependent: :destroy
  has_many :movies, through: :collections
  has_many :reviews, through: :collections

  validates :username, :email, presence: true
  validates :username, uniqueness: {scope: :email}


  # Add friendship to user
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user

# to call all your friends

def friends
  active_friends | received_friends
end


# to call your pending sent or received

def pending
  pending_friends | requested_friendships
end

def self.find_for_facebook_oauth(auth)
  user_params = auth.to_h.slice(:provider, :uid)
  user_params.merge! auth.info.slice(:email, :first_name, :last_name)
  user_params[:username] = auth.extra.raw_info.name
  user_params[:facebook_picture_url] = auth.info.image
  user_params[:token] = auth.credentials.token
  user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

  user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def self.search(search)
    where("username ILIKE ?", "%#{search}%")
    # where("first_name ILIKE ?", "%#{search}%")
    # where("last_name ILIKE ?", "%#{search}%")
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_before_action :authenticate_user!, only: [ :show]
  def show
  end

  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/_index.html.erb
<h4>Users list</h4>
<div id="users">
  <%@users.each do |user| %>
    <%unless user == current_user%>
      <div class="user">
        <ul class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-2 col-lg-6 col-lg-offset-2 user-profiles-list-minimal">
        <li>
          <div class="user-avatar">
            <% avatar_url = user.facebook_picture_url || user.photo %>
            <%= image_tag avatar_url , class: "avatar"%>
          </div>
          <p class="user-name">
            <%=user.username %>
            <span>
              <%=pluralize(user.collections.size, 'Movie')%>
              <%=pluralize(user.tags.size, 'Tag')%>
            </span>
            <span>
              <%=link_to "Add User", friendships_path(friend_id: user, user_id: current_user), method: :post %>
            </span>
          </p>
        </li>
        </ul>
      </div>
    <%end%>
  <% end %>
</div>

app/views/users/_menus.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 center">
      <div class="col-xs-12 col-sm-3">
        <%= link_to 'View', friendships_path%>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= link_to 'Add', users_path%>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= link_to 'Pending', pending_path%>
      </div>
      <div class="col-xs-12 col-sm-3">
        <%= link_to 'Sent', sent_path%>
      </div>
    </div>
<hr>

app/views/users/_users.html.erb
<% form_tag(users_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Find friends", class: 'tag-input' %>
        <%= image_submit_tag("logo-white.png", class: 'image-responsive search-logo') %>
      <% end %>

<%@users.each do |user| %>
  <%unless user == current_user%>


    <%= link_to friendships_path(friend_id: user, user_id: current_user), method: :post, class: "friend-card" do %>
      <% avatar_url = user.facebook_picture_url || user.photo %>

      <div class="user-avatar" style="background-image: url('<%= image_path avatar_url %>'); background-size: cover; width: 50px; height: 50px; border-radius: 50%; background-position: center;"></div>
      <h3><%= user.username%></h3>
      <span>
        <span style="padding-right: 5px;"><%=pluralize(user.collections.size, 'Movie')%></span>
        <span><%=pluralize(user.tags.distinct.count, 'List')%></span>
      </span>
    <% end %>

  <%end%>
<%end%>

app/views/users/index.html.erb
<div class="container" style='padding-top:80px;'>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <div class="friend-nav">
        <%= link_to 'View', friendships_path%>
        <%= link_to 'Add', users_path%>
        <%= link_to 'Pending', pending_path%>
        <%= link_to 'Sent', sent_path%>
      </div>


      <div class="text-center">
      <%= form_tag(users_path, :method => "get") do %>
       <%= text_field_tag :search, params[:search], placeholder: "Find friends", class: 'friend-input' %>
       <% image_submit_tag("logo-white.png", class: 'image-responsive search-logo') %>
       <%= submit_tag "Search", class: "btn" %>
       <% end %>
     </div>

     <% if params[:search].nil? or params[:search].strip == '' %>
     <% else %>
     <% if @users.present?%>
     <%= render 'users' %>

     <% else %>
     <p>There are no user matching: <%= params[:search] %>.</p>
     <% end %>
     <% end %>

     Soon we will have friends suggestions :)

   </div>
 </div>
</div>

app/views/users/show.html.erb
<div id="" style='background-color: #85EBBC;'>
  <div class="text-center">
    <%= image_tag 'mustachio-logo.png', class: 'main-logo-public-profile' %>
  </div>
  <div class="container public-profile text-center ">
    <div class="row ">
      <div class="col-xs-6 col-xs-offset-3">
        <div class="row ">
          <div class="col-xs-12 user-avatar">
            <% avatar_url = @user.facebook_picture_url || @user.photo %>
            <%= image_tag avatar_url , class: "avatar-xlarge"%>
            <div class="col-xs-12">
              <p class="user-name public-profile"> <%=@user.username.capitalize %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container movies-container">
    <div class="movies">
      <% if @user.collections.count == 0 %>
      <p class="no-movie">No movies the collection :(</p>
      <% else %>
      <% @user.collections.reverse.each do |collection| %>

      <div class="movie-item">
        <div class="movie-picture" style="background-image: url('<%= collection.movie.photo_url %>')"></div>
        <div class="movie-body">
          <h3><%= collection.movie.title + ' (' + collection.movie.year.to_s + ")" %></h3>

          <p>
            <% unless collection.reviews.empty? %>
            <% collection.reviews.first.my_rating.to_i.times do %>
            <i class="fa fa-star yellow"></i>
            <% end %>
            <% (5 - collection.reviews.first.my_rating.to_i).times do %>
            <i class="fa fa-star grey"></i>
            <% end %>
            <span>(<%= collection.reviews.empty? ? '' : collection.reviews.first.phrase %>)</span>
            <% end %>
          </p>
          <% unless collection.tags.size == 0 %>
          Lists:
          <%collection.tags.each do |tag| %>
          <p><%= tag.name %></p>
          <% end %>
          <% end %>

        </div>

      </div>
      <%end%>

      <% end %>
    </div>
  </div>
</div>