config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'pages#home'
    # this is the final and good code
    # resources :collections do
    #   resources :tags
    # end
    resources :collections do
      resources :reviews
      resources :tag_collections, only: [:destroy]
    end

    resources :tag_collections, only: [:create, :destroy]
    resources :tags
    resources :users
    resources :movies, only: [:show]
    resources :tag_collections, only: [:create]
    resources :friendships
    #post "search", to: "pages#search"
    # get "friends", to: "pages#friends"
    get "about", to: "pages#about"
    get "results", to: "pages#results"
    get "search", to: "pages#search"
    get "pending", to: "friendships#pending"
    get "sent", to: "friendships#sent"
    get "profile", to: "pages#profile"

     # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq' # warning everyone has access to this.. please consult the lecture notes ..lambda { |u| u.admin }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id], user_id: params[:user_id] )
    if @friendship.save
      flash[:notice] = "Friend request sent."
      redirect_to friendships_path
    else
      flash[:error] = "Unable to request friendship."
      redirect_to friendships_path
    end
  end

   def update
    @friendship = Friendship.find_by(id: params[:id])
    @friendship.update(accepted: true)
      if @friendship.save!
        redirect_to friendships_path, notice: "Successfully confirmed friend!"
      else
        redirect_to friendships_path, notice: "Sorry! Could not confirm friend!"
      end
    end

  def destroy
    friendship = Friendship.find(params[:id])
    # @friendship = current_user.friendships.find(params[:id])
   Friendship.destroy(friendship)
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end

  def show
    @tab = params[:tab] || 'tags'
    @friend = User.find(params[:id])
  end


end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_menus.html.erb
<div class="friend-nav">
  <%= link_to 'View', friendships_path%>
  <%= link_to 'Add', users_path%>
  <%= link_to 'Pending', pending_path%>
  <%= link_to 'Sent', sent_path%>
</div>
<!-- this is rendered to the index, pending, sent and the show pages-->

app/views/friendships/_pending.html.erb
<%number = 0 %>
<% current_user.received_friendships.each do |request| %>
  <%unless request.accepted == true%>
      <% number +=1 %>
  <% end %>
<% end %>
<% if number == 0 %>
<% else %>
<h4>Friend requests</h4>
<div id="users">
  <% current_user.received_friendships.each do |request| %>
    <%unless request.accepted == true%>
      <div class="user">
        <ul class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-2 col-lg-6 col-lg-offset-2 user-profiles-list-minimal">
        <li>
          <div class="user-avatar">
            <% avatar_url = request.user.facebook_picture_url || request.user.photo %>
            <%= image_tag avatar_url , class: "avatar"%>
          </div>
          <p class="user-name">
            <%=request.user.username %>
            <span>
              <%=pluralize(request.user.collections.size, 'Movie')%>
              <%=pluralize(request.user.tags.size, 'Tag')%>
            </span>
            <span>
              <%= link_to "yes",  friendship_path(id: request.id), method: "put" %>
              <%= link_to "no", friendship_path(id: request.id), method: :delete %>
            </span>
          </p>
        </li>
        </ul>
      </div>
    <%end%>
  <% end %>
</div>

<% end %>

app/views/friendships/index.html.erb
<div class="container" style='padding-top:80px;'>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%=render 'friendships/menus'%>

      <h4 class="text-center">My friends</h4>

      <% current_user.friends.each do |friend|%>
        <%= link_to friendship_path(friend), class: "friend-card" do %>
          <% avatar_url = friend.facebook_picture_url || friend.photo %>
          <div class="user-avatar" style="background-image: url('<%= image_path avatar_url %>'); background-size: cover; width: 50px; height: 50px; border-radius: 50%; background-position: center;"></div>
          <h3><%= friend.username%></h3>
          <span>
            <span style="padding-right: 5px;"><%=pluralize(friend.collections.size, 'Movie')%></span>
            <span><%=pluralize(friend.tags.distinct.count, 'List')%></span>
          </span>
        <% end %>
      <%end%>

    </div>
  </div>
</div>

app/views/friendships/pending.html.erb
<div class="container" style='padding-top:80px;'>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'friendships/menus'%>
      <%number = 0 %>
      <% current_user.received_friendships.each do |request| %>
        <%unless request.accepted == true%>
          <% number +=1 %>
        <% end %>
      <% end %>
      <% if number == 0 %>
      <h4>You don't have any friend requests...</h4>
      <% else %>
      <h4 class="text-center">Friend requests</h4>
      <% current_user.received_friendships.each do |request| %>
      <% unless request.accepted == true%>
          <div class= "friend-card">
          <% avatar_url = request.user.facebook_picture_url || request.user.photo %>
          <div class="user-avatar" style="background-image: url('<%= image_path avatar_url %>'); background-size: cover; width: 50px; height: 50px; border-radius: 50%; background-position: center;"></div>
            <h3><%=request.user.username %></h3>
            <span style="padding: 5px;"><%=pluralize(request.user.collections.size, 'Movie')%></span>
            <span  style="padding: 5px;"><%=pluralize(request.user.tags.distinct.count, 'List')%></span>
            <span  style="padding: 5px;"><%= link_to "",  friendship_path(id: request.id), method: "put", class: "fa fa-check", 'data-toggle'=> "tooltip", 'data-placement'=> "top", 'title'=> "Accept", :onclick => "alert('Input collected!')"%></span>
            <span  style="padding: 5px;"><%= link_to "", friendship_path(id: request.id), method: :delete, class: "fa fa-ban" , 'data-toggle'=> "tooltip", 'data-placement'=> "top", 'title'=> "Cancel"%></span>
            </div>

        <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/friendships/sent.html.erb
<div class="container" style='padding-top:80px;'>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'friendships/menus'%>
      <%number = 0 %>
      <% current_user.pending_friends.each do |request| %>
        <% number +=1 %>
      <% end %>
      <% if number == 0 %>
        <h4>You don't have any pending requests...</h4>
      <% else %>
        <h4 class="text-center">Requests sent</h4>
      <% current_user.pending_friends.distinct.each do |friendship| %>
          <%= link_to friendship_path(friendship), class: "friend-card" do %>
          <% avatar_url = friendship.facebook_picture_url || friendship.photo %>
          <div class="user-avatar" style="background-image: url('<%= image_path avatar_url %>'); background-size: cover; width: 50px; height: 50px; border-radius: 50%; background-position: center;"></div>
          <h3><%= friendship.username%></h3>
          <span>
            <span style="padding-right: 5px;"><%=pluralize(friendship.collections.size, 'Movie')%></span>
            <span><%=pluralize(friendship.tags.distinct.count, 'List')%></span>
          </span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/friendships/show.html.erb
<!-- <style type="text/css"> *{ border: 1px solid red !important;} </style> -->
<div class="container" style='padding-top:80px;'>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

    <%=render 'friendships/menus'%>

     <%= link_to friendship_path(@friend), class: "friend-card" do %>
        <% avatar_url = @friend.facebook_picture_url || @friend.photo %>
          <div class="user-avatar" style="background-image: url('<%= image_path avatar_url %>'); background-size: cover; width: 50px; height: 50px; border-radius: 50%; background-position: center;"></div>
         <h3><%= @friend.username%></h3>
         <span>
         <span style="padding-right: 5px;"><%=pluralize(@friend.collections.size, 'Movie')%></span>
         <span><%=pluralize(@friend.tags.distinct.count, 'List')%></span>
       </span>
     <% end %>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @friend.collections.each do |collect| %>
      <div class="col-xs-12 col-sm-3">
        <div class="friend-movie" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 30%),url('<%= image_path(collect.movie.photo_url) %>');">
          <div class="add-to-collection">
            <%= simple_form_for Collection.new, path: collections_path do |f| %>
              <%= f.hidden_field :movie_id, value: collect.movie_id %>
              <%= f.submit "Save to my collection", class: "btn center-img"%>
            <% end %>
          </div>
        </div>


      </div>
    <% end %>
  </div>
</div>



<% if false %>
  <div class="friend-content-div">
  <% @movie_id = collect.movie_id %>
  <% @movie_id.to_s %>
<!--insert add to tags form from readMe file-->
    <% current_user.tags.distinct.each do |tag| %>
      <%= simple_form_for TagCollection.new, path: tag_collections_path do |f| %>
        <%= f.hidden_field :tag_id, value: tag.id %>
        <%= f.hidden_field :collection_id, value: current_user.collections.find_by({movie_id: @movie_id}).to_s%>
        <p class="center">Add to <%= tag.name  %></p>
        <%= f.submit "+", class: "btn add-to-col center-img"%>
      <% end %>
    <% end %>
  </div>
<% end %>