config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'pages#home'
    # this is the final and good code
    # resources :collections do
    #   resources :tags
    # end
    resources :collections do
      resources :reviews
      resources :tag_collections, only: [:destroy]
    end

    resources :tag_collections, only: [:create, :destroy]
    resources :tags
    resources :users
    resources :movies, only: [:show]
    resources :tag_collections, only: [:create]
    resources :friendships
    #post "search", to: "pages#search"
    # get "friends", to: "pages#friends"
    get "about", to: "pages#about"
    get "results", to: "pages#results"
    get "search", to: "pages#search"
    get "pending", to: "friendships#pending"
    get "sent", to: "friendships#sent"
    get "profile", to: "pages#profile"

     # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq' # warning everyone has access to this.. please consult the lecture notes ..lambda { |u| u.admin }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_collections, dependent: :destroy
  has_many :collections, through: :tag_collections
  has_many :movies

  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
    @collections = current_user.collections
  end

  def create
    @tag = Tag.new(name: tag_params[:name])
    @tag.save
    movies_id = tag_params[:movie_ids].drop(1)
    collections = current_user.collections.where(movie_id: movies_id)
    collections.each do |collection|
      TagCollection.create!(collection_id: collection.id, tag_id: @tag.id)
    end

    redirect_to collections_path
  end

  def edit
  end

  def update
    @tag.update(tag_params)
    redirect_to tags_path(@tag)
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end


   private
  def set_tag
    @tag = Tag.find(params[:id])
  end
  def tag_params
    params.require(:tag).permit(:name, movie_ids:[])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="text-center list-form-container">
    <h2 class="text-center">Make your new list</h2>
    <%= simple_form_for(@tag, :html => {:class => ''})do |f| %>
    <div class=''>
      <%= f.text_field :name, label: false, placeholder: '#list_name', class: 'tag-input' %></br>


      <div class="movie-adds">
      <input type="hidden" name="tag[movie_ids][]" value="">
      <% current_user.movies.each do |movie| %>
        <label for="tag_movie_ids_<%= movie.id %>"><input class="check_boxes optional hidden" type="checkbox" value="<%= movie.id %>" name="tag[movie_ids][]" id="tag_movie_ids_<%= movie.id %>">
          <div class="movie-add" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.2) 30%), url('<%= movie.photo_url %>')" data-toggle="tooltip" data-placement="top" title="<%= movie.title %>">
            <i class="fa fa-check"></i>
          </div>
        </label>
      <% end %>
      </div>

      <%= f.submit "Create your list", class: 'btn' %>
    </div>





    <% end %>
</div>

app/views/tags/edit.html.erb
<p>Rename a your tag</p>
<%= render 'form' %>

app/views/tags/index.html.erb
<div class="container" style="margin-top: 80px">
  <p>Here are all the tags in your Collections</p>
<% current_user.tags.each do |tag| %>
  <p><%= link_to tag.name, tag_path(tag) %></p>
<% end %>

<%=link_to "Create new tag", new_tag_path %>
</div>

app/views/tags/new.html.erb
<!--   <p>Create a new tag</p> -->

<%= render 'form' %>

app/views/tags/show.html.erb
<h3><%=@tag.name%></h3>

<%= link_to "Edit", edit_tag_path %>
<%= link_to 'Delete', tag_path(@tag), method: :delete %>
<%=link_to "Back to all tags", tags_path %>

<p>Here are all the movies you tagged <%=@tag.name%></p>


<p><%@tag.collections.each do |collection|%></p>
  <% film = collection.movie.title + ' (' + collection.movie.year.to_s + ")" %>
  <p><%= link_to film %></p>
<%end%>